version: 2
jobs:
    build:
        working_directory: ~/pytorch-ocd/
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run: sudo chown -R circleci:circleci /usr/local/bin
            - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
            - run:
                name: install dependencies
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip uninstall OCD && pip install -e .[dev]
            - run:
                name: run tests
                command: |
                    . venv/bin/activate
                    pytest tests/*py
            - run:
                name: pylinting
                command:
                    pylint ./ocd/
