version: 2
jobs:
    build:
        working_directory: ~/pytorch-ocd/
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run: sudo chown -R circleci:circleci /usr/local/bin
            - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
            - run:
                name: install dependencies
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip uninstall OCD && pip install -e .[dev]
            - run:
                name: run tests
                command: |
                    . venv/bin/activate
                    pytest tests/*py
    lint:
        docker:
            - image: circleci/python:3.7
        working_directory: ~/pytorch-ocd
        steps:
            - checkout
            - run:
                name: Install Linting Tools
                command:
                    sudo pip install pycodestyle
            - run:
                name: Pycodestyle Linting
                command:
                    pycodestyle --max-line-length=120 ./ocd/
workflows:
    version: 2
    standard:
    jobs:
        - build
        - lint
